[features]
seeds = false

[programs.localnet]
prediction_game = "EPZXCy45VtSdGA7darn8LcVErMYecZS4d7XYG8pwLExb"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/lars/validator-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
